version: '3.7'
services:
  mongodb_container:
    container_name: mongodb_container
    image: mongo:latest
    env_file:
      - .env.list
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - alkyminet

  alkymi_backend:
    container_name: alkymi_backend
    build: ./
    ports:
      - 5000:5000
    depends_on:
      - mongodb_container
    env_file:
      - .env.list
    volumes:
      - .:/app
    networks:
      - alkyminet
    
volumes:
  mongodb_data_container:

networks:
  alkyminet:
    name: alkyminet
